Article:
  type: object
  config:
    fields:
      id:
        type: 'Int!'
      name:
        type: 'String!'
      comment:
        type: '[Comment]'
      author:
        type: 'Author'
      category:
        type: 'Category'